### ISSUE TITLE
Add logic to consumer from a specific partition starting at specific offset

### ISSUE THREAD

**Issue by ppatierno** [rhiot/amqp-kafka-bridge#22]
Add the possibility on the AMQP receiver side to specify partition and offset as filters : 

rhiot.io:partition-filter:ulong
rhiot.io:offset-filter:uint

in order to assign that partition to the related KafkaConsumer and start reading from the specified offset.

Following use cases can be possible with different combinations : 

- partition + offset : consumer starts to read from that partition at specified offset
- partition : consumer starts to read from that partition at last committed offset
- offset : error ! set error condition and detach link
- nothing : current behavior. Kafka consumer receives partitions after a re-balancing by Kafka server and start to read from last committed offset

Possible errors and behavior : 

- partition doesn't exist : set error condition and detach link
- negative partition or offset : set error condition and detach link

**Comment by ppatierno** [comment]
It should be defined with a filter set at source. Current Vert.x Proton implementation doesn't support it because it seems that the underlying Qpid Proton Engine doesn't support it yet.

**Comment by grs** [comment]
looks good!
