### ISSUE TITLE
Discuss about a JSON format for serializing/deserializing AMQP messages against Kafka

### ISSUE THREAD

**Issue by ppatierno** [rhiot/amqp-kafka-bridge#37]
Discuss about the possibility to use a JSON format in order to serialize/deserialize AMQP messages to/from Kafka. The current version gets only the AMQP message body and sends it to Kafka as message. The same in the opposite direction. Application and systems properties are lost.
Should they be preserved inside the Kafka message using a specific serialization format (i.e. JSON) ?

**Comment by grs** [comment]
I can see three options:
(1) just include the AMQP body (i.e. what you have now)
(2) include the entire AMQP message in the AMQP format
(3) convert the AMQP message to some other format (e.g. JSON as you suggest)

The third option is open-ended in that there are conceivably different approaches to conversion as well as different target formats. The second option is good if the receivers are all known to be coming through the bridge also (as no information will be lost). The first and third options are better if the receiver may be consuming directly from Kafka as it will then likely not be able to decode an AMQP message. The first option also works where the sender is not going through the bridge, but the receivers are.

Probably the best thing is to make it somehow easily pluggable, and then it is easy to adapt to different requirements as they arise.

**Comment by ppatierno** [comment]
+1

**Comment by ppatierno** [comment]
Added implementations and message converter description in the wiki here : 

https://github.com/rhiot/amqp-kafka-bridge/wiki/Message
